hermod:
  image: docker2.molflow.com/odin/hermod
  links:
    - mysqlhost
    - torquehost
    - pdchost
  volumes:
    - ./:/src
    - ./kinit_fejk:/usr/bin/kinit
    - ./kftp_fejk:/usr/bin/kftp

mysqlhost:
  image: docker2.molflow.com/devops/hermod_mysql
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=smr
    - MYSQL_USER=odinuser
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  ports:
    - localhost:3306:3306

torquehost:
  image: agaveapi/torque
  ports:
    - localhost:10022:22
  privileged: true

pdchost:
  image: docker2.molflow.com/devops/hermod_pdc
  ports:
    - localhost:11022:22
