hermod:
  image: docker2.molflow.com/odin/hermod
  links:
    - mysqlhost
    - torquehost
  volumes:
    - ./:/src
    - ./log:/home/odinop/hermod_systemlogs/
    - ./kinit_fejk:/usr/bin/kinit
    - ./kftp_fejk:/usr/bin/kftp

mysqlhost:
  image: docker2.molflow.com/devops/hermod_mysql
  environment:
    - MYSQL_ROOT_PASSWORD***REMOVED***
    - MYSQL_DATABASE=smr
    - MYSQL_USER=odinuser
    - MYSQL_PASSWORD=***REMOVED***

torquehost:
  image: agaveapi/torque
  ports:
    - localhost:10022:22
  privileged: true
