hermod:
  image: docker2.molflow.com/odin/hermod
  links:
    - mysql
    - torque
  volumes:
    - ./:/src
    - ./log:/home/odinop/hermod_systemlogs/

  command:
    sleep 10000

mysql:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD***REMOVED***
    - MYSQL_DATABASE=smr
    - MYSQL_USER=odinuser
    - MYSQL_PASSWORD=***REMOVED***

torque:
  image: agaveapi/torque
  ports:
    - localhost:10022:22
  privileged: true
