#!/usr/bin/expect --
set timeout 600
set prompt ":~>"
spawn /usr/bin/ktelnet -f -l donal esrange.pdc.kth.se
expect $prompt 
send ".odin/odinlist\r"
expect $prompt
send "exit\r"
expect "host."
close
wait
