#!/usr/bin/expect --
set timeout 60
spawn /usr/bin/kftp -p esrange.pdc.kth.se
expect "Name*):" 
send "donal\r"
expect "ftp> "
send "get files\r"
expect "ftp> " 
send "bye\r"
expect "Goodbye."
close
wait
