#!/usr/bin/python
import sys,os,datetime

print "### Hermod system information:"
print "###"
print "###",str(datetime.datetime.now())
print "###"

for i in os.uname():
  print "###",i

print "###"

for i in sys.argv:
  print "###",i

print "###"

sys.exit(0)
