#!/usr/bin/python

import MySQLdb
import sys

#Connect to database
last=2;
if len(sys.argv)>1:
    try:
        last=int(sys.argv[1])
    except:
        msg = sys.argv[0] +" takes one integer as argument: number of days...\n"
        sys.stderr.write(msg)
        sys.exit(0)
        
db=MySQLdb.connect(host="jet",user="gem",db="odin")
c = db.cursor(MySQLdb.cursors.SSDictCursor)
status=c.execute("""select orbit,processed,scans.freqmode,fqid,version,calibration,count(*)  
      as profiles from scans 
      natural join level2 where processed > now() - interval %s day 
      group by orbit,freqmode,calibration,version 
      order  by processed""",(last,))

row= c.fetchone()
print " orb  fm  id cal    ver                 date  pr"
while row<>None:
    try:
        print "%0.4X%4i%4i%4i%7s%21s%4i" % (row['orbit'],row['freqmode'],row['fqid'],row['calibration'],row['version'],row['processed'],row['profiles'])
        row = c.fetchone()
    except KeyboardInterrupt:
        print "Break recieved"
        break
    except Exception,inst:
        print "other error: ",inst
        print "error: ",sys.exc_info()[0]
        break

sys.stderr.write("Closing cursor...\n")
c.close()
db.close()
