#!/bin/bash

# Put a list of wanted dates in the format YYMMDD one date per row
#
# 020321
# 040404
# 991231
#
# And put it in pv.download.txt in this directory. run 'getnew' and relax.
#
cd ~/hermod/gen-nilu/
printf "put pv.download.txt\nbye\n" |lftp zardoz.nilu.no
ssh murtagh@zardoz.nilu.no "/nadir/home/murtagh/.odin-gen/genfiles_pv"
printf "get files-gen_pv\nbye\n" |lftp zardoz.nilu.no
if [ -s files-gen_pv ] ; then 
    ./makedir_pv files-gen_pv | sh -C
    gawk -F"/" -f getfiles_pv.awk files-gen_pv | lftp
fi
