#!/bin/bash

# Put a list of wanted dates in the format YYMMDD one date per row
#
# 020321
# 040404
# 991231
#
# And put it in tz.dowload.txt in this directory. run 'getnew' and relax.
#
cd ~/hermod/gen-nilu/
printf "put tz.download.txt\nbye\n" |lftp zardoz.nilu.no
ssh murtagh@zardoz.nilu.no "/nadir/home/murtagh/.odin-gen/genfiles"
printf "get files-gen\nbye\n" |lftp zardoz.nilu.no
if [ -s files-gen ] ; then 
    ./makedir files-gen | sh -C
    gawk -F"/" -f getfiles.awk files-gen | lftp
fi
