#!/usr/bin/python
from hermod.hermodBase import *
from hermod.pdc.pdc import *

"""
getL1b - Get level1b files from PDC

"""
def main():
   db = sql.connect(host=config.get('WRITE_SQL','host'), user=config.get('WRITE_SQL','user'), passwd=config.get('WRITE_SQL','passwd'), db='smr')
   a = Fetcher(db)

if __name__=="__main__":
    main()
