#!/usr/bin/python

import MySQLdb
from hermod.l1b import level1b
from hermod import hermodBase

def main():
    db = MySQLdb.connect(host="jet",user="odinuser",passwd="***REMOVED***",db="odin")
    files=sys.argv[1:]
    #for every file in argumentlist
    for file in files:
        print file
        try:
            x = Level1b(file,db)
        except HermodError,inst:
            print inst
            continue
        x.cleanDatabase()
        x.addDataL1b()
        x.moveCreateFiles('normal')
    db.close()

if __name__="__main__":
    main()
