#!/usr/bin/python

import MySQLdb
import sys
from hermod.l1b.level1b import *
from hermod.hermodBase import *

def main():
    db = MySQLdb.connect(host="jet",user="odinuser",passwd="***REMOVED***",db="odin")
    files=sys.argv[1:]
    #for every file in argumentlist
    for file in files:
        print file
        try:
            x = Level1b(file,db)
        except HermodError,inst:
            print inst
            continue
        x.cleanDatabase()
        x.addDataL1b()
        x.moveCreateFiles('normal')
    db.close()

if __name__=="__main__":
    main()
