#!/usr/bin/python

import MySQLdb
from hermod.hermodBase import *
import sys

#Connect to database
last=2;
if len(sys.argv)>1:
    try:
        last=int(sys.argv[1])
    except:
        msg = sys.argv[0] +" takes one integer as argument: number of days...\n"
        sys.stderr.write(msg)
        sys.exit(0)
db = MySQLdb.connect(host=config.get('WRITE_SQL','host'), user=config.get('WRITE_SQL','user'), passwd=config.get('WRITE_SQL','passwd'), db='smr')
c = db.cursor(MySQLdb.cursors.DictCursor)
status=c.execute("""select l2.processed,start_utc,orbit,freqmode,fqid,version,l1.nscans,l2.nscans,l2.nscans/l1.nscans as proc,verstr,hdfname from level1 as l1 join level2files as l2 using (id) where l2.processed> now() - interval %s day;""",(last,))

print "date       time      orbit  measurment date         fm  fqid  ver  ps  ts  %   verstr              logfile"
for row in c:
    print "%(processed)s%(orbit)7.4X%(start_utc)21s%(freqmode)8s%(fqid)4.2i%(version)6s%(l2.nscans)4i%(nscans)4i%(proc)5.1f%(verstr)12s%(hdfname)55s" % row
c.close()
db.close()
