#!/usr/bin/python

import MySQLdb
import sys

#Connect to database
last=2;
if len(sys.argv)>1:
    try:
        last=int(sys.argv[1])
    except:
        msg = sys.argv[0] +" takes one integer as argument: number of days...\n"
        sys.stderr.write(msg)
        sys.exit(0)
db = MySQLdb.connect(host=config.get('WRITE_SQL','host'), user=config.get('WRITE_SQL','user'), passwd=config.get('WRITE_SQL','passwd'), db=config.get('WRITE_SQL','db'))        
c = db.cursor(MySQLdb.cursors.SSDictCursor)
status=c.execute("""select orbit,processed,scans.freqmode,fqid,version,calibration,count(*)  
      as profiles from scans 
      natural join level2 where processed > now() - interval %s day 
      group by orbit,freqmode,calibration,version 
      order  by processed""",(last,))

row= c.fetchone()
rows = 0
profiles = 0
while row<>None:
    try:
        rows = rows +1
        profiles = profiles + row['profiles']
        row = c.fetchone()
    except KeyboardInterrupt:
        print "Break recieved"
        break
    except Exception,inst:
        print "other error: ",inst
        print "error: ",sys.exc_info()[0]
        break
print """
Total modes processed during %i days: %i
Total profiles processed during %i days: %i

That's %.2f modes (%.2f profiles) per hour
""" % (last,rows,last,profiles,rows/last/24.0,profiles/last/24.0)
sys.stderr.write("Closing cursor...\n")
c.close()
db.close()
